model_args:
  pretrained_model_name_or_path: "Qwen/Qwen2.5-7B"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
tokenizer_args:
  pretrained_model_name_or_path: "Qwen/Qwen2.5-7B"
template_args:
  apply_chat_template: False
  user_start_tag: "Question: "
  user_end_tag: "\n"
  asst_start_tag: "Answer: "
  asst_end_tag: "\n\n"

  # 3️⃣ —— 数据时间戳（部分数据集会把 {date_string} 渲染进提示）
  date_string: "15 Jul 2025"
